CREATE TABLE Employee (
   employee_id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   employee_name VARCHAR(255) NOT NULL,
   tel VARCHAR(50) NOT NULL,
   email VARCHAR(255) NOT NULL,
   picture VARCHAR(255) NOT NULL,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL);

   ALTER TABLE Employee ADD COLUMN address VARCHAR(255)NOT NULL,
   ADD COLUMN sex VARCHAR(255)NOT NULL,
   ADD COLUMN account_name VARCHAR(255)NOT NULL,
   ADD COLUMN account_num VARCHAR(255)NOT NULL,
   ADD COLUMN pic_bank VARCHAR(255)NOT NULL
   ;

   ALTER TABLE Employee ADD COLUMN department_id VARCHAR(255)NOT NULL;

   ALTER TABLE Employee ADD COLUMN start_date date,
   ADD COLUMN end_date date;

   ALTER TABLE employee CHANGE pic_bank bank VARCHAR(15);

   ALTER TABLE Employee ADD COLUMN username VARCHAR(255)NOT NULL;






