CREATE TABLE Employee (
   employee_id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   employee_name VARCHAR(255) NOT NULL,
   tel VARCHAR(50) NOT NULL,
   email VARCHAR(255) NOT NULL,
   picture VARCHAR(255) NOT NULL,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL);